# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

# Role-specific labels
role:common:
  - changed-files:
      - any-glob-to-any-file: 'roles/common/**/*'

role:postgresql:
  - changed-files:
      - any-glob-to-any-file: 'roles/postgresql/**/*'

role:redis:
  - changed-files:
      - any-glob-to-any-file: 'roles/redis/**/*'

role:quay:
  - changed-files:
      - any-glob-to-any-file: 'roles/quay/**/*'

role:clair:
  - changed-files:
      - any-glob-to-any-file: 'roles/clair/**/*'

role:mirror:
  - changed-files:
      - any-glob-to-any-file: 'roles/mirror/**/*'

# Playbook changes
playbook:
  - changed-files:
      - any-glob-to-any-file: 'playbooks/**/*'

# Configuration changes
configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'inventory/**/*'
          - 'ansible.cfg'

# GitHub workflows and CI/CD
ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/*'
          - '.github/actions/**/*'

# Scripts
scripts:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**/*'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/dependabot.yml'
          - 'requirements.txt'
          - 'requirements.yml'
