---
# Ansible Galaxy Requirements
# ===========================
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: containers.podman
    version: ">=1.10.0"
